# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0005_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmtNotice',
            fields=[
                ('notice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boardapp.Notice')),
            ],
            options={
                'abstract': False,
            },
            bases=('boardapp.notice',),
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
