# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0007_cmtnotice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='parent',
        ),
    ]
