# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 06:31
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0010_cmtnotice_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ht',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='boardapp.Ht'),
        ),
        migrations.AddField(
            model_name='notice',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='boardapp.Notice'),
        ),
    ]
