# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0011_auto_20160721_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ht',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Ht',
        ),
    ]
