# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0012_auto_20160721_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmtnotice',
            name='notice',
        ),
        migrations.RemoveField(
            model_name='cmtnotice',
            name='parent',
        ),
        migrations.DeleteModel(
            name='CmtNotice',
        ),
    ]
