# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0013_auto_20160721_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(default=None, null=True),
        ),
    ]
